{"name": "test02", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 1 > 1", "trace": "self = <case.ptest__pytest.Test000 object at 0x0368FAA8>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.xfail(3>2,reason='ddd')\n    def test02(self):\n        a=1\n        b=2\n        c=b-a\n        print('2222')\n>       assert c>a\nE       assert 1 > 1\n\ncase\\ptest__pytest.py:29: AssertionError"}, "start": 1592099764860, "stop": 1592099764860, "uuid": "65159c6f-22e9-429f-bdc6-9c5177fe365a", "historyId": "fbca2d8317d2911730d1ee763f263c8d", "testCaseId": "1a5cfe532c8e7fed26034c098868a89d", "fullName": "case.ptest__pytest.Test000#test02", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "ptest__pytest"}, {"name": "subSuite", "value": "Test000"}, {"name": "host", "value": "Acer"}, {"name": "thread", "value": "16604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.ptest__pytest"}]}