{"name": "test02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 1", "trace": "self = <case.ptest__pytest.Test000 object at 0x045DB7C0>\n\n    def test02(self):\n        a=1\n        b=2\n        c=b-a\n        print('2222')\n>       assert c>a\nE       assert 1 > 1\n\ncase\\ptest__pytest.py:27: AssertionError"}, "start": 1592099943912, "stop": 1592099943912, "uuid": "f35259a4-6a51-4fe5-9cf7-4887943905e5", "historyId": "fbca2d8317d2911730d1ee763f263c8d", "testCaseId": "1a5cfe532c8e7fed26034c098868a89d", "fullName": "case.ptest__pytest.Test000#test02", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "ptest__pytest"}, {"name": "subSuite", "value": "Test000"}, {"name": "host", "value": "Acer"}, {"name": "thread", "value": "1504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.ptest__pytest"}]}